stages:

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed
      - params.yaml

    params:
      - train.epochs
      - train.batch_size
      - train.imgsz
      - train.lr0
      - train.lrf
      - train.optimizer
      - train.data_yaml
      - data_version

    outs:
      - model_versions

    metrics:
      - metrics/results.json:
          cache: false


  evaluate:
    cmd: python src/evaluate.py

    deps:
      - src/evaluate.py
      - model/best.pt

    params:
      - train.data_yaml

    metrics:
      - metrics/eval.json:
          cache: false


  select_best_model:
    cmd: python src/select_best_model.py
    deps:
      - src/select_best_model.py
      - metrics/results.json
      - model_versions
      
    metrics:
      - model/best_score.txt:
          cache: false

